controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#main:
 #   path: /clientes
  #  controller: App\Controller\ClientesController::index